### Parameters:

1. values: Columns to aggregate.
2. index: Columns to use as the new row index.
3. columns: Columns to use as the new column headers.
4. aggfunc: Aggregation functions like mean, sum, count etc. By default it is mean.
5. fill_value: Value to replace missing data.
6. margins: Whether to add totals, default is false.
7. dropna: Whether to exclude missing values from the DataFrame, default is True.

In [1]:
import pandas as pd

data = {
    "region":  ["North","South","East","North","South","East",
                "North","South","East","North","South","East"],
    "month":   ["Jan","Jan","Jan","Feb","Feb","Feb",
                "Mar","Mar","Mar","Apr","Apr","Apr"],
    "product": ["Laptop","Phone","Tablet","Laptop","Phone","Tablet",
                "Laptop","Phone","Tablet","Laptop","Phone","Tablet"],
    "revenue": [2400,1600,900,1200,2400,1350,3600,800,1800,1200,3200,2700]
}

df = pd.DataFrame(data)
print(df)

   region month product  revenue
0   North   Jan  Laptop     2400
1   South   Jan   Phone     1600
2    East   Jan  Tablet      900
3   North   Feb  Laptop     1200
4   South   Feb   Phone     2400
5    East   Feb  Tablet     1350
6   North   Mar  Laptop     3600
7   South   Mar   Phone      800
8    East   Mar  Tablet     1800
9   North   Apr  Laptop     1200
10  South   Apr   Phone     3200
11   East   Apr  Tablet     2700

#### Build a pivot table showing total revenue, with region as rows and month as columns.

In [2]:
df.pivot_table(values="revenue", index="region", columns="month", aggfunc="sum")

month    Apr   Feb   Jan   Mar
region
East    2700  1350   900  1800
North   1200  1200  2400  3600
South   3200  2400  1600   800

In [5]:
df.pivot_table(values="revenue", index="region", columns="product", aggfunc=["sum", "mean"], margins = True, fill_value=0)

           sum                        mean
product Laptop Phone Tablet    All  Laptop   Phone  Tablet          All
region
East         0     0   6750   6750     0.0     0.0  1687.5  1687.500000
North     8400     0      0   8400  2100.0     0.0     0.0  2100.000000
South        0  8000      0   8000     0.0  2000.0     0.0  2000.000000
All       8400  8000   6750  23150  2100.0  2000.0  1687.5  1929.166667